vocab:
  type: Vocab
  path:
    train: datasets/Wikilingual-dataset/train.json
    dev: datasets/Wikilingual-dataset/dev.json
    test: datasets/Wikilingual-dataset/test.json
  min_freq: 3
  bos_token: <bos>
  eos_token: <eos>
  unk_token: <unk>
  pad_token: <pad>

dataset:
  train: 
    type: TextSumDataset
    path: datasets/Wikilingual-dataset/train.json
  dev:
    type: TextSumDataset
    path: datasets/Wikilingual-dataset/dev.json
  test: 
    type: TextSumDataset
    path: datasets/Wikilingual-dataset/test.json
  batch_size: 8
  num_workers: 16

model:
  name: Pointer_Generator_Wikilingual
  architecture: PointerGeneratorModel
  beam_size: 2
  is_eval: False
  use_cuda: True
  is_coverage: True
  d_model: 128
  hidden_dim: 256
  pointer_gen: True
  cov_loss_wt: 1.0
  encoder:
    hidden_dim: 256
    emb_dim: 128
    bidirectional: True
  decoder:
    emb_dim: 128
    hidden_dim: 256
    bidirectional: False
    pointer_gen: True
    is_coverage: True
  reduce_state:
    hidden_dim: 256
  label_smoothing: 0.1
  device: cuda

training:
  checkpoint_path: "checkpoints"
  learning_rate: 0.001
  cov_loss_wt: 1.0
  max_grad_norm: 2.0
  adagrad_init_acc: 0.1
  rand_unif_init_mag: 0.02
  trunc_norm_init_std: 1e-4
  eps: 1e-12
  lr_coverage: 0.15
  warmup: 1000
  patience: 5
  score: rouge-L

task: TextSumTask